#ifndef REACHABILITY_MAP_HPP
#define REACHABILITY_MAP_HPP

#include <vector>
#include <string>
#include <fstream>
#include <iostream>
#include <cmath>
#include <algorithm> // for std::max, std::min

/**
 * @brief Reachability Map Loader for C++
 * Reads binary format generated by reachability_map_generator_urdf.py
 */
class ReachabilityMap {
public:
    // Python struct.pack('fffffffiii', ...) 포맷과 1:1 대응되는 구조체
    // 4 bytes * 10 = 40 bytes Header
    struct Header {
        float resolution;
        float min_x, max_x;
        float min_y, max_y;
        float min_z, max_z;
        int dim_x, dim_y, dim_z;
    };

    ReachabilityMap() : is_loaded_(false) {}

    /**
     * @brief 바이너리 맵 파일(.bin) 로드
     * @param filepath 파일 경로
     * @return 성공 시 true
     */
    bool load(const std::string& filepath) {
        std::ifstream file(filepath, std::ios::binary);
        if (!file.is_open()) {
            std::cerr << "❌ [ReachMap] Failed to open file: " << filepath << std::endl;
            return false;
        }

        // 1. 헤더 읽기 (40 bytes)
        file.read(reinterpret_cast<char*>(&header_), sizeof(Header));

        // 2. 데이터 크기 계산 (전체 복셀 수)
        size_t total_cells = static_cast<size_t>(header_.dim_x) * header_.dim_y * header_.dim_z;
        
        // 데이터 벡터 리사이즈
        data_.resize(total_cells);

        // 3. 본문 데이터(Occupancy Grid) 읽기
        file.read(reinterpret_cast<char*>(data_.data()), total_cells);
        
        // 파일 읽기 오류 체크
        if (file.fail() && !file.eof()) {
            std::cerr << "❌ [ReachMap] Error reading data body." << std::endl;
            file.close();
            return false;
        }

        file.close();
        is_loaded_ = true;

        // 로드 정보 출력
        std::cout << "✅ [ReachMap] Loaded successfully: " << filepath << std::endl;
        std::cout << "   - Cells: " << total_cells << std::endl;
        std::cout << "   - Resolution: " << header_.resolution << " m" << std::endl;
        std::cout << "   - Bounds X: " << header_.min_x << " ~ " << header_.max_x << std::endl;
        std::cout << "   - Bounds Y: " << header_.min_y << " ~ " << header_.max_y << std::endl;
        std::cout << "   - Bounds Z: " << header_.min_z << " ~ " << header_.max_z << std::endl;
        
        return true;
    }

    /**
     * @brief 특정 좌표가 도달 가능한지 확인
     * @param x, y, z (기준 프레임 좌표, 예: link_torso_5)
     * @return true(도달 가능), false(불가능)
     */
    bool isReachable(double x, double y, double z) const {
        if (!is_loaded_) return true; // 맵이 로드 안 됐으면 필터링 패스 (안전장치)

        // 1. 작업 공간(Workspace Bounds) 체크
        if (x < header_.min_x || x > header_.max_x ||
            y < header_.min_y || y > header_.max_y ||
            z < header_.min_z || z > header_.max_z) {
            return false;
        }

        // 2. 좌표 -> 격자 인덱스 변환
        int idx_x = std::floor((x - header_.min_x) / header_.resolution);
        int idx_y = std::floor((y - header_.min_y) / header_.resolution);
        int idx_z = std::floor((z - header_.min_z) / header_.resolution);

        // 인덱스 범위 안전장치 (Clamping)
        idx_x = std::max(0, std::min(idx_x, header_.dim_x - 1));
        idx_y = std::max(0, std::min(idx_y, header_.dim_y - 1));
        idx_z = std::max(0, std::min(idx_z, header_.dim_z - 1));

        // 3. 1차원 배열 인덱스 계산 (Row-major: X -> Y -> Z 순서)
        // index = x * (Dy * Dz) + y * (Dz) + z
        size_t index = idx_x * (header_.dim_y * header_.dim_z) + 
                       idx_y * header_.dim_z + 
                       idx_z;

        if (index >= data_.size()) return false;

        // 0보다 크면 도달 가능 (Occupied)
        return data_[index] > 0;
    }

    bool isLoaded() const { return is_loaded_; }

private:
    Header header_;
    std::vector<uint8_t> data_;
    bool is_loaded_;
};

#endif
